version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      # Copy files generated in S3 bucket
      - aws s3 sync build/ s3://$BUCKET_NAME/ --delete

      # Invalidate CDN cache to load the new index.html
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"